### ISSUE TITLE
Prelude.Linear doesn't re-export Prelude Satisfactorily

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#102]
In testing this out, I (Divesh) found that Prelude.Linear exports Prelude hiding the non-linear `($)` and other related tools. This causes problems for most linear apps that have linear and non-linear code.

Maybe it should re-export all of prelude qualified as `NotLinear` or something. I'll think about it.

For simple things, using `forget` works, but this gets cumbersome for say `($)` and doesn't work for HOFs.

**Comment by aspiwack** [comment]
You can't export a module with a qualified name unfortunately. The prelude is always available with the `Prelude` qualifier, though maybe not when `-XNoImplicitPrelude` is set.

In the current linear-base, a few of the prelude functions are replaced by function which do not work well with non-linear code. `($)` is a bit complicated because to fully works, it needs impredicative inference as well. Which is not ready yet (though there is a paper!).

**Comment by Divesh-Otwani** [comment]
Yes -- this all makes sense. There's no solution to this until we have new GHC tools.
It'll just be an idiom to import Prelude qualified  as `NotLinear` or something in modules that need it.
