### ISSUE TITLE
Can we use a strict one-tuple for Unrestricted?

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#109]
And does this help us basically get a newtype without the unsafeness b/c of non-strictness and coersions?

**Comment by aspiwack** [comment]
As in

```haskell
data U a where
  U :: !a -> U a
```

Or as in an unrestricted variant of

```haskell
(# a #)
```

?

**Comment by Divesh-Otwani** [comment]
An unrestricted variant of the second one...

**Comment by aspiwack** [comment]
It would be correct (though we don't have syntax, or even support in Core, yet). However, note that `(# a #)` doesn't have sort `Type`, so it can't be passed to polymorphic functions (and so, a function of type `A #-> (# B #)` can't be passed to `fmap`).

Add to this fact that, there is an optimisation, in GHC, to do this transformation for you (though it doesn't work on `Unrestricted` yet, because of the aforementioned absence of support for an unrestricted `(# #)` in Core).

So maybe it would cost more than the benefits.

**Comment by Divesh-Otwani** [comment]
Ok, so I think this is too minor to keep as an issue so I'm closing it.
