### ISSUE TITLE
Mutable vectors (and possibly arrays) should support having zero elements inside

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#149]
Currently, our linear mutable `Array` and `Vector` implementations require the collection to always contain at least one element inside. 

Especially when using a `Vector`, it is common to start with an empty vector and append new elements to it. Having it require an element to start with is unusual, so we should support having zero elements inside (this includes resizing to zero elements) and provide an `empty` method.

I think this choice stems from `Unsafe.MutableArray.newMutArr`'s precondition that the size should be positive. However, I did a few quick tests and it seems to be happy when the size is 0 too. So we can probably relax that requirement and the `Vector` and `Array` changes would follow.

This issue is broken up from: #146

**Comment by aspiwack** [comment]
The empty array is not particularly useful. But I don't see a reason why it shouldn't exist. That being said, it's fairly natural for an array to be initialised. Whereas an empty vector really need no values inside.

> I think this choice stems from `Unsafe.MutableArray.newMutArr`'s precondition that the size should be positive. However, I did a few quick tests and it seems to be happy when the size is 0 too.

Yes, I think it was a shortcut that may have since been fixed. There was #100 where HashMaps have been fixed to be able to start empty at least. It may not be a problem at all, so go for it.
