### ISSUE TITLE
Ensure effects happen in order when using `Unsafe.MutableArray`

### ISSUE THREAD

**Issue by facundominguez** [tweag/linear-base#177]
Currently, linear mutable arrays and vectors use Unsafe.MutableArray, which requires forcing evaluation of seemingly pure expressions that have side effects. However, there is little control on the order of side-effects.

```Haskell
case writeMutArray ix val arr of
  () -> k
```
is equivalent to `seq (writeMutArray ix val arr) k` which the documentation of [Control.Parallel.pseq](https://www.stackage.org/haddock/lts-16.13/parallel-3.2.2.0/Control-Parallel.html#v:pseq) warns that might evaluate effects in a different order.

Similarly for reading arrays we do
```Haskell
case readMutArray ix arr of
  (# a #) -> f a
```
which for the same reasons as `seq`, it could be reordered to `f (case readMutArray ix arr of (# a #) -> a)` if GHC thinks that `f` is strict.

It turns out the only mechanism GHC offers to order effects is `GHC.Conc.pseq`, which can be used to fix the write case, and less clearly the read case because the levity of the boxed tuple prevents it from being given to `pseq`.

I think the best fix for linear base would be to make the interface of `Unsafe.MutableArray` harder to misuse. For instance,
```Haskell
writeMutArr :: HasCallStack => MutArr# a -> Int -> a -> b -> b
writeMutArr mutArr (I# ix) val k =
  case doWrite of _ -> GHC.Exts.lazy k
  where
    doWrite = runRW# $ \stateRW -> writeArray# mutArr ix val stateRW

-- | Read from a given mutable array arr, given an index
-- in [0, size(arr)-1]
--
-- This returns an unboxed tuple to give the callee the
-- ability to evaluate the function call without evaluating
-- the final result.
readMutArr :: HasCallStack => MutArr# a -> Int -> (a -> b) -> b
readMutArr mutArr (I# ix) k =
  case doRead of (# _, a #) -> GHC.Exts.lazy (k a)
  where
    doRead = runRW# $ \stateRW -> readArray# mutArr ix stateRW
```

The fix above relies on continuations and on the definition of [pseq](https://www.stackage.org/haddock/lts-16.13/base-4.13.0.0/src/GHC-Conc-Sync.html#pseq) being
```
pseq a b = a `seq` lazy b
```

**Comment by Divesh-Otwani** [comment]
I like this -- as this was a major source of confusion when developing early on. 

- I think we should just use `pseq` instead of relying on the underlying definition and using case statements paired with `GHC.Exts.lazy`. So, `pseq doWrite k` for `writeMutArr` should suffice. (If `pseq` changes at some point in the future, this won't have to.)
- The reasoning by which we know `pseq` is a reliable way to force order of evaluation should be documented or linked to.

**Comment by facundominguez** [comment]
Yeah, `pseq doWrite k` doesn't work because `doWrite` is unlifted, and `pseq` wants an lifted type.

**Comment by aspiwack** [comment]
I think that, currently `Unsafe.MutableArray` is only used in the implementation of the `Array`, module. If this is the case, it will actually be easier, clearer, and more efficient to just inline `Unsafe.MutableArray` in `Array`, and force the ordering with `IO`'s `(>>=)`.

**Comment by aspiwack** [comment]
You know what, #180 (specifically, the language in the PR description), made me think of something. There seems to be some confusion about what can be lazy and what cannot. Or at least maybe there is. And each time we have some discussion about laziness, we have to have a look at whether we are being overly lazy or not.

Let's make our lives simpler. Not only should we inline whatever we did in `Unsafe.MutableArray` and disapear said module. But we ought to make a new _safe_ array module for an _unlifted_ array type. Then build the lifted array type without any unsafe functions. In the unlifted array module, we don't have any laziness issue (and ordering will be handled by `IO`). And, because it's safe, we will be able to breath and not think about laziness when making the lazier array.

Note: in unlifted array type, we still want the elements of the array to be at a lifted type, and we don't want to force them when we don't have to.
