### ISSUE TITLE
What immutable array type should linear base use?

### ISSUE THREAD

**Issue by aspiwack** [tweag/linear-base#185]
In the `Array.Destination`, the `alloc` function has type

```haskell
alloc :: Int -> (DArray a #-> ()) #-> Vector a
```

This is saying that our type of immutable array is `Vector a`. There is nothing wrong with it, to be honest. The vector library is standard enough to be part of a standard library at this point. I just want to make sure that we all agree on this.

**Comment by utdemir** [comment]
I do not have any concerns about having `vector` dependency or exposing it as part of the public interface.

However, I wonder if that specific function should use `Data.Array.Mutable.Linear.Array` instead. I do understand that there are many good reasons to use the `vector` library, since it likely is more performant and comes with more utilities. However, it also does seem a bit strange to use an array type from an external library instead of using one of our own. If it is because of a shortcoming of our linear Array library, we should fix that.

I am not sure about this, but it might be possible to have a function like `Data.Array.Mutable.Linear.Array #-> Unrestricted Data.Vector.Vector` which runs in constant time (I'm even less sure about the other way around). If that is possible, the case for returning an `Array` instead of ` Vector` is stronger.

I know that you mentioned "immutable array type" in the title. Does the result being "immutable" is an important point? Because if we were to use our Arrays, we could both do linear stuff with them, or still convert it to an immutable `Vector` when necessary.

---

I think another relevant papercut is about the naming of our vector-like collections on `linear-base`, since we also have:

* `Data.Vector.Linear`, which is not a linear interface to `Data.Vector`, but a length indexed "vector". (It happens to use `Data.Vector` underneath, but just as an implementation detail)
* `Data.Vector.Mutable.Linear`, which is arguably the most similar to `vector` library, and might be seen as a linear interface to `Data.Vector.Mutable`.

This all is a bit confusing. I will create another issue about this.

**Comment by aspiwack** [comment]
Well, my question was about immutable vectors, which we can used unrestrictedly. It's unrelated to the question of whether we also want to eliminate destinations to a mutable type.

For things which can be unrestricted, I'd like, as much as possible, to use types from the normal Haskell ecosystem. So that linear code and normal code interoperates. `Vector` is fine for this, so is the `Array` type from base. Though I think I like `Vector` a little bit more, for the case at hand.

**Comment by utdemir** [comment]
Just to note that, with #205 merged, freezing a mutable array results on a `Data.Vector.Vector`.

**Comment by aspiwack** [comment]
It _does_ seem like we are settling on `Vector` indeed.

**Comment by Divesh-Otwani** [comment]
I'm good with `Data.Vector.Vector`. Can we close?

**Comment by aspiwack** [comment]
Yes, I think that it's `Vector`, until someone complains.
