### ISSUE TITLE
Infinite Streams?

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#252]
**Is your feature request related to a problem? Please describe.**

Inside `Streaming.Internal.Produce` we have 

```haskell
data AffineStream f m r where
  AffineStream :: x %1-> (x %1-> m (Either (f x) r)) -> (x %1-> m r) -> AffineStream f m r
```

and versions of `take`, `zip` and `until` that work on this type. We use this to encode infinite stream-like things in a finite way. We have `stdin :: AffineStream (Of String) IO ()` and use `\n -> take n stdin` to provide a finite-stream API and so on.

Maybe we can expose this infinite API directly in some coherent way. That would be cool.

**Describe alternatives you've considered**
Keeping everything internal if we can't devise a coherent API is a safe option.

**Comment by aspiwack** [comment]
For more context, the discussion, on these started at https://github.com/tweag/linear-streams/pull/31#pullrequestreview-489341937.

What's the idea? Infinite streams don't play well with linear streams, since linearity forces you to consume the entirety of the stream. As a result, you can really consume a single infinite stream in a program (for instance `stdin`) (well you could zip infinite streams together and consume that one, effectively consuming several streams, but only at one point in the program).

Even if your stream is not infinite, you sometimes want to exit early: if I want to read the first 3 lines of a file, it's a pity if I'm forced to read the other 50k lines, just because of linear streams.

As it turns out, all these streams that are naturally infinite, or, more generally, that we want to interrupt, have a natural internal state as well. In the file example, it would be a `Handle`.

The type above is really a classical type of streams (a pair of an internal state and a next-state function (_i.e._ the arguments to `unfold`)), paired with a function to interrupt the state.

This is a good type when defining infinite streams. But it will be inconvenient for many other combinators. So an api for such interruptible streams would have some combinators like `take`, and `zip` (crucial combinators which let us make the stream finite). But most of the typical combinators of `Stream` ought to stay on the standard stream type: they will be more efficient.

**Comment by aspiwack** [comment]
This has been done long ago. See commit a2c069b7bf74d081bd85167e3d2907b524cd1e00 which was part of the merge in #210 .
