### ISSUE TITLE
Cabal doesn't play nice with hedgehog

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#264]
**Describe the bug**
Using `cabal test` when there are failed tests sometimes crashes because the log files hedgehog write cannot be read because of the locale in the nix-shell determining the encoding to read with and the locale of the system determining the log file hedgehog writes.

Basically we should get back to just using stack and having a cleaner setup.

**Comment by Divesh-Otwani** [comment]
Referring to the issue we had with stack: #199

**Comment by utdemir** [comment]
> cannot be read because of the locale in the nix-shell determining the encoding to read with and the locale of the system determining the log file hedgehog writes.

I am not entirely sure if this is the case. Because I tried fixing this issue with different locale combinations both by using things like `with-utf8` on Haskell side, and setting my system locale, and it did not help. It definitely seems like a locale issue, but I'm not sure if that is either `hedgehog` or `nix` is doing the wrong thing. It feels like a `cabal-install` issue to me.

> Basically we should get back to just using stack and having a cleaner setup.

I think the common denominator of Haskell projects is using `cabal`, so even if we use `stack` for developing, I'd argue for having a working `cabal-install` setup.

**Comment by aspiwack** [comment]
> I think the common denominator of Haskell projects is using `cabal`, so even if we use `stack` for developing, I'd argue for having a working `cabal-install` setup.

I don't think that this is an accurate description of the situation. We don't do anything special for `cabal` in almost every one of our libraries, I don't see a particular reason why this one would be different.

Libraries are meant to be installed via Hackage, and this will work (stack uses cabal anyway). If you can't run the tests locally with cabal, I don't think we should care.

However, this whole story is very very puzzling. Whether #199 or this one. There doesn't seem to be much sense or reason behind this. And why is linear-based particularly affected? And why does it happen randomly? So many questions!

For the time being, though, I'd argue for whatever is the cheapest, most stable solution.

**Comment by utdemir** [comment]
> I don't think that this is an accurate description of the situation. We don't do anything special for cabal in almost every one of our libraries, I don't see a particular reason why this one would be different.

Oh, I agree with this. Of course if `cabal-install` works if we don't do anything special, we shouldn't do anything special. But if it, for some reason, requires us to do something special in `linear-base`, we should :). Or fix `cabal-install` if it requires us to do something that we shouldn't.

> Libraries are meant to be installed via Hackage, and this will work (stack uses cabal anyway). If you can't run the tests locally with cabal, I don't think we should care.

Well, I'd say that they also meant to contributed to, and in this case, especially for a "simple" library like `linear-base`, people would like to be able to run the tests locally. I'm just arguing it should be possible to use `cabal-install` while developing the library; I, for one, couldn't start working on `linear-base` until I got `cabal-install` working.

> For the time being, though, I'd argue for whatever is the cheapest, most stable solution.

I do agree here. I expect things to get better when GHC 9 is released.

**Comment by aspiwack** [comment]
> I'm just arguing it should be possible to use `cabal-install` while developing the library; I, for one, couldn't start working on `linear-base` until I got `cabal-install` working.

I must admit that I found this to be a rather astounding statement. Projects typically support a single way to build. If Stack is advertised I see no reason to reach for Cabal, and vice-versa. As it happens the de facto standard for Tweag Haskell projects is to built with Stack, so that's what we strive to support. I'm happy to accept any patch that patch that facilitates the life of someone preferring to use cabal install. But this is not something that I'm willing to spend company money on, for the time being.

**Comment by aspiwack** [comment]
I think this has been solved somehow. The CI works with both stack and cabal anyway. Let me close.
