### ISSUE TITLE
nix error: cannot coerce null to a string

### ISSUE THREAD

**Issue by chikeabuah** [tweag/linear-base#268]
**Describe the bug**
When I run `stack build` I get the nix coercion error shown in the attached image.

**To Reproduce**
I downloaded the linear-base repo and nix, then ran stack build.

**Environment**
 - OS name + version: macOS Mojave Version 10.14.3
 - Version of the code: master branch (unchanged)

**Additional context**
<img width="1271" alt="nixerror" src="https://user-images.githubusercontent.com/2280440/100105981-f7c59e80-2e35-11eb-9b86-642394faaa90.png">

**Comment by joprice** [comment]
Looks like this is caused by the `glibcLocales` modification here 

https://github.com/utdemir/nixpkgs/commit/647a878e061b1b63efd2094eb9e546c2a7aa0d58#diff-71cf0d63355f78e3ae66dff9521cb419b983e123c1c1d090fffa499c6a716068R143

which is only available on linux:

```nix
glibcLocales = if stdenv.hostPlatform.libc == "glibc" then callPackage ../development/libraries/glibc/locales.nix { } else null;
```

Making it optional gets you past this:

``` nix
    export LANG="en_US.UTF-8";
  '' + stdenv.lib.optionalString (glibcLocales != null) ''
    export LOCALE_ARCHIVE=${glibcLocales}/lib/locale/locale-archive
  '' + ''
```

But you might hit other issues with newer versions of OSX (I'm on 11.0.1, not sure what version it was when the "libsystem" errors started). For that, I think the branch nix fork will need to be rebased against a newer nix nightly commit. I forked it and did so and it started building.

**Comment by utdemir** [comment]
Thank you for finding the culprit @joprice! It definitely make sense to me.

I'll rebase our fork, apply the fix and try to find a Mac to confirm if it works.

**Comment by joprice** [comment]
No problem. This should be obvious from the error, but I forgot that I also had to remove `happy = self.happy_1_20_0;`, since the latest master has 1.20.
