### ISSUE TITLE
Generalize (.) ?

### ISSUE THREAD

**Issue by ekmett** [tweag/linear-base#309]
**Is your feature request related to a problem? Please describe.**
Right now folks are generally used to being able to throw `(.)` at their problems. Can `Prelude.Linear`'s `(.)` be generalized?

**Describe the solution you'd like**
```haskell
(.) :: (b %m -> c) %m -> (a %m -> b) %m -> (a %m -> c)
(.) f g x = f (g x)
```

**Describe alternatives you've considered**
Defining a one-off linear `(.)` can also be done, but this subsumes both. With LinearHaskell turned off it seems like this falls back to the regular `(.)`.

**Additional context**

**Comment by ekmett** [comment]
This seems to hold, mutatis mutandis for a whole bunch of other 'common' operations like `flip`, `curry`, `uncurry`, `const` that all seem to survive the same treatment in various ways. I didn't see if this was discussed previously. If it was I'd appreciate a pointer.

**Comment by aspiwack** [comment]
I just want to let you know that we've seen this issue (and any other we haven't replied to yet). However, with the Icfp deadline approaching, we find ourselves quite busy. We'll be back to you after the deadline has passed.

**Comment by ekmett** [comment]
Having dug into this further and tried a bunch of the generalizations out I'm getting a better sense of why `linear-base` is currently not choosing to be ambitious with this regard, in particular with the current fairly limited set of multiplicities.

**Comment by aspiwack** [comment]
Right. Some of the possible types are not even allowed by the proposal, and are accepted coincidentally because we take shortcuts in the typechecker (we not taking any unsound shortcut, but stabilising them would close the door to potential extensions).

The main problem that we are facing is that multiplication of multiplicities is not well-supported by the typechecker yet.

That being said, I thought of a way to have more general types without having the most general types possible. Do have a look at #319 (which I claim closes this issue, complain loudly if you disagree!)
