### ISSUE TITLE
Array.alloc requires CPS, but Array.get etc. don't?

### ISSUE THREAD

**Issue by ewtoombs** [tweag/linear-base#318]
The only way for Array.alloc to put restrictions on its output is to pass it as input to a linear function.
https://github.com/tweag/linear-base/blob/095d478f90af5afdd0a546b04708c097763f431e/src/Data/Array/Mutable/Linear/Internal.hs#L62
That makes sense.

What about Array.get?! What about all the other functions that return Arrays? How is it able to restrict use of its Array output? Why can't Array.alloc do the same?
https://github.com/tweag/linear-base/blob/095d478f90af5afdd0a546b04708c097763f431e/src/Data/Array/Mutable/Linear/Internal.hs#L122

What stops me from doing this:
```
alloc 16 0 \a ->
    let (Ur x, a1) = get 4 a
        a2 = set 8 3 a1
        a3 = set 8 4 a1
        (Ur y, _) = get 8 a2
        (Ur z, _) = get 8 a3
        in Ur (y, z)
```
`get 4 a` puts no restrictions on what I may do with `a1`, so I use it twice. Why not? And if it is putting restrictions on a1, how? And why can't `alloc` put restrictions on its new array in the same way?

**Comment by aspiwack** [comment]
Hi @ewtoombs, thanks for your interest.

You are quite right to point this out because it's a very subtle issue. On which, probably, we ought to write more.

First, I don't know if it helps much, but I don't like seeing `alloc` as being in CPS. It's a matter of perspective, of course, but I find it more helpful to see the last argument of `alloc` as being a scope in which the array lives (or, at least, stays mutable).

That being said, why can't you write your example? From a typing rule perspective, you can use tan exprssion unrestrictedly whenever the expression doesn't have linear free variable. In our case, in `get 4 a`, `a` is linear, therefore `(Ur x, a1)` must be linear as well. It's not a matter for `x`, since it's shielded by the `Ur`, but `a1` must absolutely be used linearly. So you can't define both `a2` and `a3`. Similarly, is `a2` is defined, it is linear, so `get 8 a2` is linear and you can't drop the resulting array.

I don't know how you like to think of your Haskell program, but the intuition I like to have about this is: `get 4 a` is a thunk, if I don't consume it linearly, then I'm not guaranteed to consume the values in its closure (here `a`) linearly.

Another way to think about that is that linear functions don't create unique pointer, but they preserve unique pointers.

This is a bit of a shortcut still, there is a related discussion in #130 (where it is discussed how that last intuition is but an approximation of the big picture).

**Comment by ewtoombs** [comment]
I think I have found a way to explain, if I state the rule of linearity differently from how it was stated in the [first presentation](https://www.youtube.com/watch?v=t0mhvd3-60Y) on it that I saw. It stated f is defined linear iff "*If* (f u) is consumed exactly once, *then* u is consumed exactly once." This was the cause of the confusion. By this rule, `get` really doesn't make any guarantees at all if I consume its output more than once. If I restate the rule as

> "u is consumed exactly as many times as (f u) is consumed."

then it all makes sense. `get` actually *does* allow you to use its output more than once, but it links the number of uses to its input. And there IS a restriction on its input. This restriction thus originates with alloc and is propagated through get.

If this view is right, I am inclined to close this issue.

**Comment by Divesh-Otwani** [comment]
> "u is consumed exactly as many times as (f u) is consumed."
> Patterns without CPS may be used to propagate linearity, but CPS must be used as the origin of linearity.

Correct and very well put :smiley: 

I think I said something similar when I was first figuring out the implementation of linear types. This stuff should probably go in the user guide (or at least, be phrased closer to how you've described it).

**Comment by ewtoombs** [comment]
For that matter, where is the user guide?

**Comment by Divesh-Otwani** [comment]
https://github.com/tweag/linear-base/blob/master/docs/USER_GUIDE.md

**Comment by ewtoombs** [comment]
This is more of a general question about the linear typing not really related to linear-base, but why can't get have some kind of a signature like `Int -> Array a %0-> a`, the 0 indicating get does not destroy its input or include it in any part of its output? The ergonomics of get right now are insane.

**Comment by aspiwack** [comment]
In this particular case, where the array only contains unrestricted `a`-s, it may be possible to give such a type signature to `get`. It doesn't scale to a situation where the inner `a` is linear, but a lot of things get weirder in this case, anyway.

The status of the `0` multiplicity is still in flux, but let's say that one of the possible designs would allow such a signature (as well as `length :: [a] %0-> Ur Int`, etc…).

We also have come up with another, maybe more general, approach to reduce the syntactic bureaucracy of linear types. We just wrote a paper about it, and it's freshly available in Arxiv: [Linear Constraints](https://arxiv.org/abs/2103.06127).

**Comment by ewtoombs** [comment]
Wow, published Mar 10! This is brand new! :D

**Comment by aspiwack** [comment]
Quite :slightly_smiling_face: .

This has been in the back of or mind for a long time. But we finally got around to figure it out this year.
