### ISSUE TITLE
Understanding for core typeclass differences from base Prelude

### ISSUE THREAD

**Issue by machinedgod** [tweag/linear-base#402]
Hi,
I was looking forward to switch my new project over to `linear-base` so I can test things out more with Linear types.
Thing is, I am having issues with standard typeclasses and generalized deriving: in order to derive Num, for example, there is a large amount of fragmented typeclasses to support this: FromInteger, Ring, Semiring, AdditiveIdentity, MultiplicativeIdentity, and so on.

From one perspective, I do understand the benefit of fragmenting these (as then more types can only implement instantiate specific ones), but from the other - I feel it diverges too much from base Prelude in order to be useful long term, and I feel this fragmentation is working in the opposite direction of overloaded names being useful.

**Describe the solution you'd like**
Ideally - I'd like a reasoning for this new fragmentation, and I'd like if it could somehow be an 'opt-in' thing, so that I can simply take standard Prelude code, switch over to `Prelude.Linear` and have everything compile.
It is more than possible that something was off with my setup as well, and this is how linear-base operates normally; in this case, I'd like to be told what can I do to resolve it (as I'd really like to use `linear-base`)

**Describe alternatives you've considered**
Simply switching back to base Prelude, as I value consistency and long term compatibility more than experimentation.

**Comment by aspiwack** [comment]
We've allowed ourselves a rather limited amount of departure from base. This change is, indeed, not related to linear types all that much (well, a linear `Num` class is probably not quite as useful as its non-linear relative, so there's that).

The reasoning behind this change is that the main role of the `Num` class is to serve to overload arithmetic operators. In my experience, though, there are few types besides the ones which already implement `Num` in base which support all the `Num` operations. Which ended up, in a number of practical setting, with someone defining `Num` instances where several of the method were implemented as `error "not supported"`.

The `(+)`, `(-)`, `(*)` symbols are, in my view, too precious, too central in algebra, to be grouped together. So we broke the thing off.

Unfortunately, I don't know of any way to make this opt in (just like if you want to derive `Traversable` you have to write `deriving (Functor, Foldable, Traversable)`. That would have been my preference as well.

I don't know your use case, but it's quite possibly fine to just use base's `Num` class, and ignore the linear-base hierarchy if you don't like it. Functions rarely need to be linear on numbers, since they are `Movable`.

**Comment by machinedgod** [comment]
Thank you for the exhaustive answer! Everything you say makes a lot of sense to me too; GHC is moving slowly in this direction as well, over the years, with adding Applicative, Semigroup, MonadFail and so on...

However - I am just not entirely sure it warrants learning new set of typeclasses for version 0.1.0. For now, I will return to standard base, but will give linear-base a chance a bit further down the line, maybe after few more versions.

Once again - thank you, both for the explanation and very fine work on linear-base.
