### ISSUE TITLE
Generalize allocation

### ISSUE THREAD

**Issue by treeowl** [tweag/linear-base#407]
I know my linear intuition isn't always that great, but it seems to me that we can probably generalize allocation functions to work with linear monads. We have

```haskell
empty ::
  forall k v b.
  Keyed k =>
  Int ->
  (HashMap k v %1 -> Ur b) %1 ->
  Ur b
```

Couldn't we generalize that?

```haskell
emptyM ::
  forall k v b.
  (Keyed k, Monad m) =>
  Int ->
  (HashMap k v %1 -> m (Ur b)) %1 ->
  m (Ur b)
```

This would let us use it in the linear continuation monad transformer (#408)

```haskell
newtype ContT r m a = ContT ((a %1-> m r) %1-> m r)
-- Yes, this is really an instance of everything it should be

emptyC :: (Keyed k, Monad m) => Int -> ContT (Ur b) m (HashMap k v)
```

**Comment by treeowl** [comment]
Oh, as for why we might want that. Imagine we want to do something with multiple `HashMap`s (and similar containers). We can then write things like

```haskell
do
  hm1 <- emptyC 300
  ...
  liftIO whatever
  ...
  hm2 <- emptyC 400
  ...
```

**Comment by treeowl** [comment]
No, this won't work as described; it's too powerful. I could write something like

```haskell
gronk :: Keyed k => Int -> (HashMap k v %1-> (Option (HashMap k v), Ur b)) %1-> (Option (HashMap k v), Ur b)
gronk = emptyM

foom :: Keyed k => Int -> HashMap k v
foom cap = case gronk cap (\hm -> (Some hm, Ur ())) of
  (Some m, _) -> m
  _ -> undefined
```

and probably break everything.

**Comment by treeowl** [comment]
For some monads, we can just do the simple thing.

```haskell
newHM :: MonadIO m => Int -> m (HashMap k v)
newHM = liftIO . newHMIO
```

Living in (linear) `IO`, this `HashMap` can't be abused. But that's rather limited.

**Comment by aspiwack** [comment]
I think it really must be an `Ur` of something. That's because if forces all the linear stuff (where all the effects are) to be in the outer thunk, then evaluating this thunk is guaranteed to execute all the effects. This guarantees that effects are well sequenced and that the result is deterministic.

(In a case where I was doing some `malloc` and `free` in the implementation, failing to forcing the `Ur` thunk even created some memory-corruption errors)

As for the motivation: I'm not sure that `ContT` is the answer, here. There is a discussion in #130 about how to improve allocation functions (I've actually made progress there, but I need a bit of time to write up my current thoughts).

**Comment by treeowl** [comment]
Yeah, I think this ticket is basically a half-baked duplicate of that one. I'll close it.
