### ISSUE TITLE
Linear State to avoid handle passing boilerplate.

### ISSUE THREAD

**Issue by expipiplus1** [tweag/linear-base#95]
I'm excited to use linear types to make sure that my handles are never left open. 

It looks like a real pain though to have to manually thread a handle in and out of operations in which it is used (`(Handle #-> RIO (Unrestricted Text, Handle)` for example)

The type signature `h #-> m (a, h)` looks a lot like a state monad. Is it possible to abstract over this pattern? If so, would it be possible to add an example of this to this repo?

**Comment by aspiwack** [comment]
Firstly: thanks for your interest and encouragements:slightly_smiling_face: 

On your question, it is indeed possible to use a linear state monad. `Control.Monad.Linear` exposes a `StateT` transformer which you could exploit to this effect.

With an important caveat: there is currently no way to abstract over whether it returns `Unrestricted a` or `a`. The current version assumes `a`, so you still have to manually unpack `Unrestricted`. It's also possible to define a state transformer which always returns an unrestricted `a`. It's very much a case of picking your poison. This particular problem should be addressed in the coming months: it is due to the implementation of Linear Haskell itself, not this library.

A bigger difficulty though. Is that you may have more than one `Handle` or other things that you may want to carry around like this. As soon as you have two handles, the `StateT` pattern wouldn't help you. Or, rather: I don't know how to make use of `StateT` to reduce the syntax overhead when there is more than one linear quantity being threaded.

Improving on this state of affairs requires bona fide research. We've got some ideas in the pipelines, hopefully they will pan out.

All this being said: yes we can, and probably should, add an example of using `State` or `StateT` for such a case.

**Comment by expipiplus1** [comment]
> A bigger difficulty though. Is that you may have more than one Handle or other things that you may want to carry around like this. As soon as you have two handles, the StateT pattern wouldn't help you. Or, rather: I don't know how to make use of StateT to reduce the syntax overhead when there is more than one linear quantity being threaded.

Many effect systems allow having the same effect at different types (`State Foo` and `State Bar`) simultaneously. It would be a pain to have to give every `Handle` a distinct tag at the type level though. 

While it is certainly is a testament to Haskell's flexibility to be able to do this kind of resource management solely in user code it's also difficult to replace the ease of resource management that languages such as Rust and C++ enjoy.

**Comment by aspiwack** [comment]
This is a good point. In fact, I'm pretty sure that everything that we do in terms of resource management (and typestate) with linear types could be done with indexed monads instead. It's what Idris used to do too. Linear types mean to be more convenient than indexed monads. I hope they are.

There is still a long way to go to be as convenient as Rust for this particular use-case. We probably never will get quite there. But I hope we can be closer than we are now.

**Comment by Divesh-Otwani** [comment]
I think this issue would be more helpful if we could frame it in terms of a specific example, perhaps one with many file handles that we need to open. We could then compare the ease of writing that program in C++, in non-linear Haskell and with the linear IO monad, perhaps wrapped in a state transformer. 

I think this would clearly inform development and point us to a concrete goal: make it so we have an API that's good for this example.

**Comment by aspiwack** [comment]
Since this conversation has died off. And considering that I consider the sort of type-level programming required to make a multiple-effect state monad is beyond the scope of this library, let me close this issue.
